### ISSUE TITLE
Tem um bug ali

### ISSUE THREAD

**Issue by avsthiago** [CoisasAvancadas/viserionAngular#1]
Tem um bug na linha 5

**Comment by Tibola** [comment]
Nossa equipe estará verificando.

**Comment by avsthiago** [comment]
Obregado

**Comment by Tibola** [comment]
A equipe já verificou, o erro da linha 5 está corrigido.
Talvez ele foi pra linha 25, mas estamos monitorando.
Aguardamos seu feedback!
Obrigado!
